### ISSUE TITLE
Range of score values

### ISSUE THREAD

**Issue by AsishKotaru550** [christophschuhmann/improved-aesthetic-predictor#15]
What is the absolute minimum and maximum values the the model returns

**Comment by AsishKotaru550** [comment]
Never mind. The images are rated from 1 to 10; found it here: https://laion.ai/blog/laion-aesthetics/

**Comment by MengHao666** [comment]
> https://laion.ai/blog/laion-aesthetics/

what is the difference between this repo and  https://laion.ai/blog/laion-aesthetics/ ? I feel confused.
